#!/usr/bin/env zsh
set -euo pipefail

workdir=${1:-/tmp/irondome}
mkdir -p "$workdir"

baseline="$workdir/network-baseline.txt"
cur="$workdir/network-current.txt"

ts=$(date +%s)
out="$workdir/irondome-$ts.txt"
latest="$workdir/irondome-latest.txt"

if [[ ! -f "$baseline" ]]; then
  arp -a | sort > "$baseline"
fi

{
  echo "=== Iron Dome Buddy (evidence report) ==="
  echo "time: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "host: $(scutil --get ComputerName 2>/dev/null || hostname)"
  echo "user: $(whoami)"
  echo

  echo "[network] ARP diff vs baseline"
  arp -a | sort > "$cur"
  diff -u "$baseline" "$cur" || true
  echo

  echo "[network] Active TCP connections (top 40)"
  netstat -anv | egrep 'tcp' | head -40 || true
  echo

  echo "[host] Listening ports (common)"
  lsof -nP -iTCP -sTCP:LISTEN | egrep ':(22|80|443|8080|11434)\b' || true
  echo

  echo "[ollama] Status"
  if command -v ollama >/dev/null 2>&1; then
    ollama ps || true
  else
    echo "ollama not found"
  fi
  echo

  echo "[logs] macOS unified log quick scan (last 10m)"
  log show --style syslog --last 10m --predicate 'eventMessage CONTAINS[c] "deny" OR eventMessage CONTAINS[c] "failed" OR eventMessage CONTAINS[c] "invalid" OR eventMessage CONTAINS[c] "blocked" OR eventMessage CONTAINS[c] "ssh"' 2>/dev/null | tail -120 || true
  echo

  echo "[irondome] detector inputs"
  echo "- evidence: $latest"
  echo "- alerts:   $workdir/alerts-latest.txt (generated by irondome-detect.zsh)"
  echo "- actions:  $workdir/actions-latest.txt (generated by irondome-respond.zsh)"
} > "$out"

# Update latest pointer (atomic-ish)
cp -f "$out" "$latest"

echo "[irondome] wrote $out"
