#!/usr/bin/env zsh
set -euo pipefail

# Guest verification helper for Iron Dome.
#
# Pending codes are generated by irondome-detect.zsh into <workdir>/pending-verifications.json
#
# Usage:
#   irondome-verify.zsh pending <workdir>
#   irondome-verify.zsh approve <code> <workdir>

cmd=${1:-pending}
shift || true

workdir=${2:-${1:-/tmp/irondome}}
[[ "$cmd" == "approve" ]] && workdir=${2:-/tmp/irondome}

pending_json="$workdir/pending-verifications.json"

case "$cmd" in
  pending)
    python3 - "$pending_json" <<'PY'
import json, os, sys, time

path = sys.argv[1]
if not os.path.exists(path):
  print(f"no pending file: {path}")
  raise SystemExit(0)

try:
  data = json.load(open(path, 'r', encoding='utf-8'))
except Exception:
  print("cannot parse pending file")
  raise SystemExit(1)

items = data.get('pending') if isinstance(data, dict) else None
if not isinstance(items, list) or not items:
  print("no pending verifications")
  raise SystemExit(0)

print(f"pending: {path}")
for it in items:
  if not isinstance(it, dict):
    continue
  code = it.get('code','')
  name = it.get('name','')
  ip = it.get('ip','')
  mac = it.get('mac','')
  first = it.get('first_seen','')
  print(f"- code={code} ip={ip} mac={mac} name={name} first_seen={first}")
PY
    ;;
  approve)
    code=${1:-""}
    if [[ -z "$code" ]]; then
      echo "missing code" >&2
      exit 2
    fi
    match_json=$(python3 - "$pending_json" "$code" <<'PY'
import json, os, sys

path, code = sys.argv[1], sys.argv[2]
if not os.path.exists(path):
  print("no pending file")
  raise SystemExit(2)

data = json.load(open(path, 'r', encoding='utf-8'))
items = data.get('pending') if isinstance(data, dict) else None
if not isinstance(items, list):
  print("no pending entries")
  raise SystemExit(2)

match = None
keep = []
for it in items:
  if not isinstance(it, dict):
    continue
  if str(it.get('code','')) == str(code) and not match:
    match = it
    continue
  keep.append(it)

if not match:
  print("code not found")
  raise SystemExit(3)

data['pending'] = keep
with open(path, 'w', encoding='utf-8') as f:
  json.dump(data, f, ensure_ascii=False, indent=2)

print(json.dumps(match, ensure_ascii=False))
PY
)

    echo "$match_json"

    mac=$(python3 -c 'import json,sys; print((json.loads(sys.stdin.read()) or {}).get("mac",""))' <<< "$match_json" 2>/dev/null || true)
    name=$(python3 -c 'import json,sys; print((json.loads(sys.stdin.read()) or {}).get("name",""))' <<< "$match_json" 2>/dev/null || true)
    ip=$(python3 -c 'import json,sys; print((json.loads(sys.stdin.read()) or {}).get("ip",""))' <<< "$match_json" 2>/dev/null || true)

    if [[ -z "$mac" ]]; then
      echo "approved code, but missing mac in entry" >&2
      exit 0
    fi

    label="$name"
    [[ -n "$ip" ]] && label="${label} ${ip}"
    /bin/zsh "$HOME/.continue/scripts/irondome-allowlist.zsh" add-mac "$mac" "$label" >/dev/null || true
    echo "added to allowlist: $mac${label:+ ($label)}"
    ;;
  *)
    echo "unknown cmd" >&2
    exit 2
    ;;
esac
